version: "3.8"
services:
  py:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - $PWD/work:/home/jovyan/work
      - conda:/opt/conda
      - conda-cofig:/home/jovyan/.conda

volumes:
  conda: {}
  conda-cofig: {}
